name: AppStore Connect deployment
on: 
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
jobs:
  deploy:
    name: Deploy To Production
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_PROJECT: ${{ 'PasswordGenerator.xcodeproj' }}
      XC_SCHEME: ${{ 'PasswordGenerator' }}
      IS_CI: 'true'
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Import Codesign Certs
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATE_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PWD }}
      - name: 'Download Provisioning Profiles'
        id: provisioning
        uses: apple-actions/download-provisioning-profiles@v1
        with: 
          bundle-id: 'com.rkreutz.PasswordGenerator'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
