name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '11.5' }}
      XC_PROJECT: ${{ 'PasswordGenerator.xcodeproj' }}
      XC_SCHEME: ${{ 'PasswordGenerator' }}
      IS_CI: 'true'
    steps:
    - name: Select Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Prepare Build
      run: brew bundle --verbose
    - name: SwiftLint
      run: swiftlint lint --reporter emoji --strict
    - name: Build the project
      run: /usr/bin/xcodebuild build -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
